kind: pipeline
name: arm64
platform:
  os: linux
  arch: arm64


steps:
- name: setup-env
  image: ubuntu:16.04
  commands:
  - apt update -y
  - apt install -y build-essential
  - gcc --version
  - uname -a

