kind: pipeline
name: arm64-linux-gcc

platform:
  os: linux
  arch: arm64

steps:
- name: arm64-linux-gcc
  image: ubuntu:xenial
  environment:
    C_COMPILER: gcc
  commands:
  - apt-get -qq update
  - apt-get install -qq -y build-essential git indent libtool libz-dev software-properties-common yasm autoconf
  - gcc --version
  - env

---
kind: pipeline
name: arm64-linux-clang

platform:
  os: linux
  arch: arm64

steps:
- name: arm64-linux-clang
  image: ubuntu:xenial
  environment:
    C_COMPILER: clang
  commands:
  - apt-get -qq update
  - apt-get install -qq -y build-essential git indent libtool libz-dev software-properties-common yasm autoconf
  - apt-get install -qq -y clang
  - clang --version
  - env
